DROP TABLE IF EXISTS dogs, candies, drinks, vehicles;

CREATE TABLE dogs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  weight TEXT
);

CREATE TABLE candies (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  flavor TEXT NOT NULL
);

CREATE TABLE drinks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  alcohol TEXT NOT NULL,
  flavor TEXT NOT NULL
);

CREATE TABLE vehicles (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  wheels INTEGER NOT NULL,
  speed TEXT NOT NULL
)